name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install flake8

      - name: Run flake8
        run: flake8 .

  test:
  name: Run unit tests with Nose
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install nose

    - name: Run unit tests with nose
      run: nosetests

